export const NS_PER_SEC = 1e9
export const MS_PER_NS = 1e-6

export const HYPERSESSION_RECORD = 'pane:record'

export const SESSION_ADD_DATA = 'SESSION_ADD_DATA'
export const SESSION_USER_DATA = 'SESSION_USER_DATA'
export const SESSION_PTY_DATA = 'SESSION_PTY_DATA'

export const HYPERSESSION_CLEAR = 'HYPERSESSION_CLEAR'
export const HYPERSESSION_TOGGLE = 'HYPERSESSION_TOGGLE'
